import type { Metadata } from "next";
import styles from "./globals.module.scss";

export const metadata: Metadata = {
	title: "Digitall",
	description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
  	return (
		<html className={styles.html} lang="en">
			<body className={styles.body}>
				{children}
			</body>
		</html>
	);
}
